openapi: 3.0.3
info:
  title: Movie Sumo API
  description: |-
    

  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Movie
    description: Everything about Movies

paths:
  /movie/{movieId}:
    get:
      tags:
        - Movie
      summary: find movie by Id
      description: returns a single Movie
      parameters:
        - name: movieId
          in: path
          description: id of Movie to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '400':
          description: invalid Id supplied
        '404':
          description: movie not found
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 7051
        title:
          type: string
          example: Departed